### ISSUE TITLE
Support for Electron 5?

### ISSUE THREAD

**Issue by paulius005** [kapetan/osx-mouse#10]
I get the following when trying to compile with Electron 5:
```
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.15.0 | darwin | x64
gyp info find Python using Python version 2.7.15 found at "/usr/local/opt/python@2/bin/python2.7"
gyp http GET https://electronjs.org/headers/v5.0.11/node-v5.0.11-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v5.0.11/node-v5.0.11-headers.tar.gz
gyp http GET https://electronjs.org/headers/v5.0.11/SHASUMS256.txt
gyp http 200 https://electronjs.org/headers/v5.0.11/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [ '/Users/p/dev/desktop/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/p/dev/desktop/node_modules/osx-mouse/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/p/dev/desktop/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/p/.electron-gyp/5.0.11/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/p/.electron-gyp/5.0.11',
gyp info spawn args   '-Dnode_gyp_dir=/Users/p/dev/desktop/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/p/.electron-gyp/5.0.11/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/p/dev/desktop/node_modules/osx-mouse',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/addon/source/addon.o
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:221:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:118:1: note: expanded from here
ToBoolean
^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:2387:3: note: 'ToBoolean' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("ToBoolean can never throw. Use Local version.",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:221:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
X(bool, Boolean)
^
../../nan/nan_converters_43_inl.h:37:15: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
              ^
<scratch space>:125:1: note: expanded from here
BooleanValue
^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:2432:3: note: 'BooleanValue' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:103:37: warning: 'New' is deprecated: Use maybe version [-Wdeprecated-declarations]
  return scope.Escape(v8::Function::New( isolate
                                    ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:4026:10: note: 'New' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1064:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                           ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:2407:3: note: 'ToString' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1855:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                           ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1861:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(key, value);
                           ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1867:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(index, value);
                           ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3268:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1873:32: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
                               ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3313:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1879:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(key));
                                               ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3313:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1884:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(index));
                                               ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3317:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:2698:
../../nan/nan_object_wrap.h:24:25: warning: 'IsNearDeath' is deprecated: Garbage collection internal state should not be relied on. [-Wdeprecated-declarations]
    assert(persistent().IsNearDeath());
                        ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:571:3: note: 'IsNearDeath' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:2698:
../../nan/nan_object_wrap.h:67:18: warning: 'MarkIndependent' is deprecated: Objects are always considered independent. Use MarkActive to avoid collecting otherwise dead weak handles. [-Wdeprecated-declarations]
    persistent().MarkIndependent();
                 ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:553:3: note: 'MarkIndependent' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:2698:
../../nan/nan_object_wrap.h:124:26: warning: 'IsNearDeath' is deprecated: Garbage collection internal state should not be relied on. [-Wdeprecated-declarations]
    assert(wrap->handle_.IsNearDeath());
                         ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:571:3: note: 'IsNearDeath' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
../source/mouse.h:20:32: error: expected ')'
                static void Initialize(Handle<Object> exports);
                                             ^
../source/mouse.h:20:25: note: to match this '('
                static void Initialize(Handle<Object> exports);
                                      ^
../source/addon.cc:3:23: error: expected ')'
void Initialize(Handle<Object> exports) {
                      ^
../source/addon.cc:3:16: note: to match this '('
void Initialize(Handle<Object> exports) {
               ^
../source/addon.cc:4:20: error: use of undeclared identifier 'exports'
        Mouse::Initialize(exports);
                          ^
13 warnings and 3 errors generated.
make[1]: *** [Release/obj.target/addon/source/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/p/dev/desktop/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/p/.nvm/versions/node/v10.15.0/bin/node" "/Users/p/dev/desktop/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=5.0.11" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/p/dev/desktop/node_modules/osx-mouse
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.15.0 | darwin | x64
gyp info find Python using Python version 2.7.15 found at "/usr/local/opt/python@2/bin/python2.7"
gyp http GET https://electronjs.org/headers/v5.0.11/node-v5.0.11-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v5.0.11/node-v5.0.11-headers.tar.gz
gyp http GET https://electronjs.org/headers/v5.0.11/SHASUMS256.txt
gyp http 200 https://electronjs.org/headers/v5.0.11/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [ '/Users/p/dev/desktop/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/p/dev/desktop/node_modules/osx-mouse/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/p/dev/desktop/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/p/.electron-gyp/5.0.11/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/p/.electron-gyp/5.0.11',
gyp info spawn args   '-Dnode_gyp_dir=/Users/p/dev/desktop/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/p/.electron-gyp/5.0.11/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/p/dev/desktop/node_modules/osx-mouse',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/addon/source/addon.o
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:221:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:118:1: note: expanded from here
ToBoolean
^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:2387:3: note: 'ToBoolean' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("ToBoolean can never throw. Use Local version.",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:221:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
X(bool, Boolean)
^
../../nan/nan_converters_43_inl.h:37:15: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
              ^
<scratch space>:125:1: note: expanded from here
BooleanValue
^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:2432:3: note: 'BooleanValue' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:103:37: warning: 'New' is deprecated: Use maybe version [-Wdeprecated-declarations]
  return scope.Escape(v8::Function::New( isolate
                                    ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:4026:10: note: 'New' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1064:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                           ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:2407:3: note: 'ToString' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1855:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                           ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1861:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(key, value);
                           ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1867:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(index, value);
                           ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3268:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1873:32: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
                               ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3313:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1879:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(key));
                                               ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3313:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
../../nan/nan.h:1884:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(index));
                                               ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:3317:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:2698:
../../nan/nan_object_wrap.h:24:25: warning: 'IsNearDeath' is deprecated: Garbage collection internal state should not be relied on. [-Wdeprecated-declarations]
    assert(persistent().IsNearDeath());
                        ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:571:3: note: 'IsNearDeath' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:2698:
../../nan/nan_object_wrap.h:67:18: warning: 'MarkIndependent' is deprecated: Objects are always considered independent. Use MarkActive to avoid collecting otherwise dead weak handles. [-Wdeprecated-declarations]
    persistent().MarkIndependent();
                 ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:553:3: note: 'MarkIndependent' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
In file included from ../source/mouse.h:6:
In file included from ../../nan/nan.h:2698:
../../nan/nan_object_wrap.h:124:26: warning: 'IsNearDeath' is deprecated: Garbage collection internal state should not be relied on. [-Wdeprecated-declarations]
    assert(wrap->handle_.IsNearDeath());
                         ^
/Users/p/.electron-gyp/5.0.11/include/node/v8.h:571:3: note: 'IsNearDeath' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/p/.electron-gyp/5.0.11/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../source/addon.cc:1:
../source/mouse.h:20:32: error: expected ')'
                static void Initialize(Handle<Object> exports);
                                             ^
../source/mouse.h:20:25: note: to match this '('
                static void Initialize(Handle<Object> exports);
                                      ^
../source/addon.cc:3:23: error: expected ')'
void Initialize(Handle<Object> exports) {
                      ^
../source/addon.cc:3:16: note: to match this '('
void Initialize(Handle<Object> exports) {
               ^
../source/addon.cc:4:20: error: use of undeclared identifier 'exports'
        Mouse::Initialize(exports);
                          ^
13 warnings and 3 errors generated.
make[1]: *** [Release/obj.target/addon/source/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/p/dev/desktop/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/p/.nvm/versions/node/v10.15.0/bin/node" "/Users/p/dev/desktop/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=5.0.11" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/p/dev/desktop/node_modules/osx-mouse
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/Users/p/dev/desktop/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/p/dev/desktop/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.error (/Users/p/dev/desktop/node_modules/rxjs/internal/Subscriber.js:158:26)
    at Subscriber._error (/Users/p/dev/desktop/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/p/dev/desktop/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/p/dev/desktop/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/p/dev/desktop/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/p/dev/desktop/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/p/dev/desktop/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (/Users/p/dev/desktop/node_modules/rxjs/internal/Subscriber.js:145:22)
```

looking here: https://github.com/electron-userland/electron-spellchecker/issues/132

> Electron 5.0 includes a version of V8 that has finally removed v8::Handle for good, and native Node.js addons that still use it will need to be updated before they can be used with Electron 5.0

Is anyone else experiencing this? On node `v10.15.0` and Electron `5.0.11`

**Comment by paulius005** [comment]
@poiru does your fork work with Electron 5 and later?

**Comment by paulius005** [comment]
nvm this is fixed here: https://github.com/kapetan/osx-mouse/pull/9

**Comment by paulius005** [comment]
closing

**Comment by rwwagner90** [comment]
@paulius005 that PR with the fix has not been merged. Any chance we could get it in?
